server:
  port: 8081
  servlet:
    context-path: /userSystem
  thymeleaf:
      cache: false
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: leemer
app:
  sso:
    login:
      url: http://localhost:8080/login
    logout:
      url: http://localhost:8080/logout